// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRateLimiter is an autogenerated mock type for the RateLimiter type
type MockRateLimiter struct {
	mock.Mock
}

type MockRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiter) EXPECT() *MockRateLimiter_Expecter {
	return &MockRateLimiter_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx, deviceIp
func (_m *MockRateLimiter) Acquire(ctx context.Context, deviceIp string) (bool, error) {
	ret := _m.Called(ctx, deviceIp)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, deviceIp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, deviceIp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceIp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRateLimiter_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockRateLimiter_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceIp string
func (_e *MockRateLimiter_Expecter) Acquire(ctx interface{}, deviceIp interface{}) *MockRateLimiter_Acquire_Call {
	return &MockRateLimiter_Acquire_Call{Call: _e.mock.On("Acquire", ctx, deviceIp)}
}

func (_c *MockRateLimiter_Acquire_Call) Run(run func(ctx context.Context, deviceIp string)) *MockRateLimiter_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRateLimiter_Acquire_Call) Return(_a0 bool, _a1 error) *MockRateLimiter_Acquire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRateLimiter_Acquire_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRateLimiter_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: ctx, deviceIp
func (_m *MockRateLimiter) Reset(ctx context.Context, deviceIp string) error {
	ret := _m.Called(ctx, deviceIp)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deviceIp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRateLimiter_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockRateLimiter_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceIp string
func (_e *MockRateLimiter_Expecter) Reset(ctx interface{}, deviceIp interface{}) *MockRateLimiter_Reset_Call {
	return &MockRateLimiter_Reset_Call{Call: _e.mock.On("Reset", ctx, deviceIp)}
}

func (_c *MockRateLimiter_Reset_Call) Run(run func(ctx context.Context, deviceIp string)) *MockRateLimiter_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRateLimiter_Reset_Call) Return(_a0 error) *MockRateLimiter_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRateLimiter_Reset_Call) RunAndReturn(run func(context.Context, string) error) *MockRateLimiter_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRateLimiter creates a new instance of MockRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiter {
	mock := &MockRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
