// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenStore is an autogenerated mock type for the TokenStore type
type MockTokenStore struct {
	mock.Mock
}

type MockTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStore) EXPECT() *MockTokenStore_Expecter {
	return &MockTokenStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, user_uid, tid
func (_m *MockTokenStore) Add(ctx context.Context, user_uid string, tid string) error {
	ret := _m.Called(ctx, user_uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, user_uid, tid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockTokenStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - user_uid string
//   - tid string
func (_e *MockTokenStore_Expecter) Add(ctx interface{}, user_uid interface{}, tid interface{}) *MockTokenStore_Add_Call {
	return &MockTokenStore_Add_Call{Call: _e.mock.On("Add", ctx, user_uid, tid)}
}

func (_c *MockTokenStore_Add_Call) Run(run func(ctx context.Context, user_uid string, tid string)) *MockTokenStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenStore_Add_Call) Return(_a0 error) *MockTokenStore_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_Add_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTokenStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// IsAllowed provides a mock function with given fields: ctx, user_uid, tid
func (_m *MockTokenStore) IsAllowed(ctx context.Context, user_uid string, tid string) (bool, error) {
	ret := _m.Called(ctx, user_uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, user_uid, tid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, user_uid, tid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, user_uid, tid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type MockTokenStore_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - user_uid string
//   - tid string
func (_e *MockTokenStore_Expecter) IsAllowed(ctx interface{}, user_uid interface{}, tid interface{}) *MockTokenStore_IsAllowed_Call {
	return &MockTokenStore_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, user_uid, tid)}
}

func (_c *MockTokenStore_IsAllowed_Call) Run(run func(ctx context.Context, user_uid string, tid string)) *MockTokenStore_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenStore_IsAllowed_Call) Return(_a0 bool, _a1 error) *MockTokenStore_IsAllowed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_IsAllowed_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockTokenStore_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, user_uid, tid
func (_m *MockTokenStore) Remove(ctx context.Context, user_uid string, tid string) error {
	ret := _m.Called(ctx, user_uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, user_uid, tid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockTokenStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - user_uid string
//   - tid string
func (_e *MockTokenStore_Expecter) Remove(ctx interface{}, user_uid interface{}, tid interface{}) *MockTokenStore_Remove_Call {
	return &MockTokenStore_Remove_Call{Call: _e.mock.On("Remove", ctx, user_uid, tid)}
}

func (_c *MockTokenStore_Remove_Call) Run(run func(ctx context.Context, user_uid string, tid string)) *MockTokenStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenStore_Remove_Call) Return(_a0 error) *MockTokenStore_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_Remove_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTokenStore_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function with given fields: ctx, user_uid
func (_m *MockTokenStore) RemoveAll(ctx context.Context, user_uid string) error {
	ret := _m.Called(ctx, user_uid)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, user_uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockTokenStore_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - user_uid string
func (_e *MockTokenStore_Expecter) RemoveAll(ctx interface{}, user_uid interface{}) *MockTokenStore_RemoveAll_Call {
	return &MockTokenStore_RemoveAll_Call{Call: _e.mock.On("RemoveAll", ctx, user_uid)}
}

func (_c *MockTokenStore_RemoveAll_Call) Run(run func(ctx context.Context, user_uid string)) *MockTokenStore_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_RemoveAll_Call) Return(_a0 error) *MockTokenStore_RemoveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_RemoveAll_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenStore_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenStore creates a new instance of MockTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStore {
	mock := &MockTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
