// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	params "github.com/adityakw90/service-user/internal/core/domain/params"
)

// MockDeviceRepository is an autogenerated mock type for the DeviceRepository type
type MockDeviceRepository struct {
	mock.Mock
}

type MockDeviceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepository) EXPECT() *MockDeviceRepository_Expecter {
	return &MockDeviceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, device
func (_m *MockDeviceRepository) Create(ctx context.Context, device *model.Device) (*model.Device, error) {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Device) (*model.Device, error)); ok {
		return rf(ctx, device)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Device) *model.Device); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Device) error); ok {
		r1 = rf(ctx, device)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeviceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.Device
func (_e *MockDeviceRepository_Expecter) Create(ctx interface{}, device interface{}) *MockDeviceRepository_Create_Call {
	return &MockDeviceRepository_Create_Call{Call: _e.mock.On("Create", ctx, device)}
}

func (_c *MockDeviceRepository_Create_Call) Run(run func(ctx context.Context, device *model.Device)) *MockDeviceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Device))
	})
	return _c
}

func (_c *MockDeviceRepository_Create_Call) Return(_a0 *model.Device, _a1 error) *MockDeviceRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Device) (*model.Device, error)) *MockDeviceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, device
func (_m *MockDeviceRepository) Delete(ctx context.Context, device *model.Device) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Device) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeviceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.Device
func (_e *MockDeviceRepository_Expecter) Delete(ctx interface{}, device interface{}) *MockDeviceRepository_Delete_Call {
	return &MockDeviceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, device)}
}

func (_c *MockDeviceRepository_Delete_Call) Run(run func(ctx context.Context, device *model.Device)) *MockDeviceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Device))
	})
	return _c
}

func (_c *MockDeviceRepository_Delete_Call) Return(_a0 error) *MockDeviceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceRepository_Delete_Call) RunAndReturn(run func(context.Context, *model.Device) error) *MockDeviceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByFingerprint provides a mock function with given fields: ctx, fingerprint
func (_m *MockDeviceRepository) GetByFingerprint(ctx context.Context, fingerprint string) (*model.Device, error) {
	ret := _m.Called(ctx, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for GetByFingerprint")
	}

	var r0 *model.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Device, error)); ok {
		return rf(ctx, fingerprint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Device); ok {
		r0 = rf(ctx, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fingerprint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_GetByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFingerprint'
type MockDeviceRepository_GetByFingerprint_Call struct {
	*mock.Call
}

// GetByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fingerprint string
func (_e *MockDeviceRepository_Expecter) GetByFingerprint(ctx interface{}, fingerprint interface{}) *MockDeviceRepository_GetByFingerprint_Call {
	return &MockDeviceRepository_GetByFingerprint_Call{Call: _e.mock.On("GetByFingerprint", ctx, fingerprint)}
}

func (_c *MockDeviceRepository_GetByFingerprint_Call) Run(run func(ctx context.Context, fingerprint string)) *MockDeviceRepository_GetByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeviceRepository_GetByFingerprint_Call) Return(_a0 *model.Device, _a1 error) *MockDeviceRepository_GetByFingerprint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_GetByFingerprint_Call) RunAndReturn(run func(context.Context, string) (*model.Device, error)) *MockDeviceRepository_GetByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockDeviceRepository) GetByID(ctx context.Context, id int64) (*model.Device, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Device, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Device); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDeviceRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockDeviceRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDeviceRepository_GetByID_Call {
	return &MockDeviceRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDeviceRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockDeviceRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockDeviceRepository_GetByID_Call) Return(_a0 *model.Device, _a1 error) *MockDeviceRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*model.Device, error)) *MockDeviceRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUID provides a mock function with given fields: ctx, uid
func (_m *MockDeviceRepository) GetByUID(ctx context.Context, uid string) (*model.Device, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUID")
	}

	var r0 *model.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Device, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Device); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_GetByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUID'
type MockDeviceRepository_GetByUID_Call struct {
	*mock.Call
}

// GetByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockDeviceRepository_Expecter) GetByUID(ctx interface{}, uid interface{}) *MockDeviceRepository_GetByUID_Call {
	return &MockDeviceRepository_GetByUID_Call{Call: _e.mock.On("GetByUID", ctx, uid)}
}

func (_c *MockDeviceRepository_GetByUID_Call) Run(run func(ctx context.Context, uid string)) *MockDeviceRepository_GetByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeviceRepository_GetByUID_Call) Return(_a0 *model.Device, _a1 error) *MockDeviceRepository_GetByUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_GetByUID_Call) RunAndReturn(run func(context.Context, string) (*model.Device, error)) *MockDeviceRepository_GetByUID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockDeviceRepository) List(ctx context.Context, pagination *params.PaginationParam, filter *params.DeviceListFilterParam) (*model.Devices, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.Devices
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *params.PaginationParam, *params.DeviceListFilterParam) (*model.Devices, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *params.PaginationParam, *params.DeviceListFilterParam) *model.Devices); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Devices)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *params.PaginationParam, *params.DeviceListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeviceRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *params.PaginationParam
//   - filter *params.DeviceListFilterParam
func (_e *MockDeviceRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockDeviceRepository_List_Call {
	return &MockDeviceRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockDeviceRepository_List_Call) Run(run func(ctx context.Context, pagination *params.PaginationParam, filter *params.DeviceListFilterParam)) *MockDeviceRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*params.PaginationParam), args[2].(*params.DeviceListFilterParam))
	})
	return _c
}

func (_c *MockDeviceRepository_List_Call) Return(_a0 *model.Devices, _a1 error) *MockDeviceRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_List_Call) RunAndReturn(run func(context.Context, *params.PaginationParam, *params.DeviceListFilterParam) (*model.Devices, error)) *MockDeviceRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userId, pagination, filter
func (_m *MockDeviceRepository) ListByUserID(ctx context.Context, userId int64, pagination *params.PaginationParam, filter *params.DeviceListFilterParam) (*model.Devices, error) {
	ret := _m.Called(ctx, userId, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 *model.Devices
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *params.PaginationParam, *params.DeviceListFilterParam) (*model.Devices, error)); ok {
		return rf(ctx, userId, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *params.PaginationParam, *params.DeviceListFilterParam) *model.Devices); ok {
		r0 = rf(ctx, userId, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Devices)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *params.PaginationParam, *params.DeviceListFilterParam) error); ok {
		r1 = rf(ctx, userId, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockDeviceRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int64
//   - pagination *params.PaginationParam
//   - filter *params.DeviceListFilterParam
func (_e *MockDeviceRepository_Expecter) ListByUserID(ctx interface{}, userId interface{}, pagination interface{}, filter interface{}) *MockDeviceRepository_ListByUserID_Call {
	return &MockDeviceRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userId, pagination, filter)}
}

func (_c *MockDeviceRepository_ListByUserID_Call) Run(run func(ctx context.Context, userId int64, pagination *params.PaginationParam, filter *params.DeviceListFilterParam)) *MockDeviceRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*params.PaginationParam), args[3].(*params.DeviceListFilterParam))
	})
	return _c
}

func (_c *MockDeviceRepository_ListByUserID_Call) Return(_a0 *model.Devices, _a1 error) *MockDeviceRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, int64, *params.PaginationParam, *params.DeviceListFilterParam) (*model.Devices, error)) *MockDeviceRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, device
func (_m *MockDeviceRepository) Update(ctx context.Context, device *model.Device) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Device) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDeviceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.Device
func (_e *MockDeviceRepository_Expecter) Update(ctx interface{}, device interface{}) *MockDeviceRepository_Update_Call {
	return &MockDeviceRepository_Update_Call{Call: _e.mock.On("Update", ctx, device)}
}

func (_c *MockDeviceRepository_Update_Call) Run(run func(ctx context.Context, device *model.Device)) *MockDeviceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Device))
	})
	return _c
}

func (_c *MockDeviceRepository_Update_Call) Return(_a0 error) *MockDeviceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Device) error) *MockDeviceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceRepository creates a new instance of MockDeviceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepository {
	mock := &MockDeviceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
