// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockUserFileRepository is an autogenerated mock type for the UserFileRepository type
type MockUserFileRepository struct {
	mock.Mock
}

type MockUserFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFileRepository) EXPECT() *MockUserFileRepository_Expecter {
	return &MockUserFileRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userFile
func (_m *MockUserFileRepository) Create(ctx context.Context, userFile *model.UserFile) (*model.UserFile, error) {
	ret := _m.Called(ctx, userFile)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserFile) (*model.UserFile, error)); ok {
		return rf(ctx, userFile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserFile) *model.UserFile); ok {
		r0 = rf(ctx, userFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserFile) error); ok {
		r1 = rf(ctx, userFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserFileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userFile *model.UserFile
func (_e *MockUserFileRepository_Expecter) Create(ctx interface{}, userFile interface{}) *MockUserFileRepository_Create_Call {
	return &MockUserFileRepository_Create_Call{Call: _e.mock.On("Create", ctx, userFile)}
}

func (_c *MockUserFileRepository_Create_Call) Run(run func(ctx context.Context, userFile *model.UserFile)) *MockUserFileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserFile))
	})
	return _c
}

func (_c *MockUserFileRepository_Create_Call) Return(_a0 *model.UserFile, _a1 error) *MockUserFileRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileRepository_Create_Call) RunAndReturn(run func(context.Context, *model.UserFile) (*model.UserFile, error)) *MockUserFileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userFile
func (_m *MockUserFileRepository) Delete(ctx context.Context, userFile *model.UserFile) error {
	ret := _m.Called(ctx, userFile)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserFile) error); ok {
		r0 = rf(ctx, userFile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserFileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserFileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userFile *model.UserFile
func (_e *MockUserFileRepository_Expecter) Delete(ctx interface{}, userFile interface{}) *MockUserFileRepository_Delete_Call {
	return &MockUserFileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userFile)}
}

func (_c *MockUserFileRepository_Delete_Call) Run(run func(ctx context.Context, userFile *model.UserFile)) *MockUserFileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserFile))
	})
	return _c
}

func (_c *MockUserFileRepository_Delete_Call) Return(_a0 error) *MockUserFileRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserFileRepository_Delete_Call) RunAndReturn(run func(context.Context, *model.UserFile) error) *MockUserFileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUserFileRepository) GetByID(ctx context.Context, id int64) (*model.UserFile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.UserFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.UserFile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.UserFile); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserFileRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserFileRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserFileRepository_GetByID_Call {
	return &MockUserFileRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserFileRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockUserFileRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserFileRepository_GetByID_Call) Return(_a0 *model.UserFile, _a1 error) *MockUserFileRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*model.UserFile, error)) *MockUserFileRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUID provides a mock function with given fields: ctx, uid
func (_m *MockUserFileRepository) GetByUID(ctx context.Context, uid string) (*model.UserFile, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUID")
	}

	var r0 *model.UserFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserFile, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserFile); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileRepository_GetByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUID'
type MockUserFileRepository_GetByUID_Call struct {
	*mock.Call
}

// GetByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockUserFileRepository_Expecter) GetByUID(ctx interface{}, uid interface{}) *MockUserFileRepository_GetByUID_Call {
	return &MockUserFileRepository_GetByUID_Call{Call: _e.mock.On("GetByUID", ctx, uid)}
}

func (_c *MockUserFileRepository_GetByUID_Call) Run(run func(ctx context.Context, uid string)) *MockUserFileRepository_GetByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserFileRepository_GetByUID_Call) Return(_a0 *model.UserFile, _a1 error) *MockUserFileRepository_GetByUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileRepository_GetByUID_Call) RunAndReturn(run func(context.Context, string) (*model.UserFile, error)) *MockUserFileRepository_GetByUID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockUserFileRepository) List(ctx context.Context, pagination *param.PaginationParam, filter *param.UserFileListFilterParam) (*model.UserFiles, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.UserFiles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserFileListFilterParam) (*model.UserFiles, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserFileListFilterParam) *model.UserFiles); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFiles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.UserFileListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserFileRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.UserFileListFilterParam
func (_e *MockUserFileRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockUserFileRepository_List_Call {
	return &MockUserFileRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockUserFileRepository_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.UserFileListFilterParam)) *MockUserFileRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.UserFileListFilterParam))
	})
	return _c
}

func (_c *MockUserFileRepository_List_Call) Return(_a0 *model.UserFiles, _a1 error) *MockUserFileRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileRepository_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.UserFileListFilterParam) (*model.UserFiles, error)) *MockUserFileRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userFile
func (_m *MockUserFileRepository) Update(ctx context.Context, userFile *model.UserFile) error {
	ret := _m.Called(ctx, userFile)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserFile) error); ok {
		r0 = rf(ctx, userFile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserFileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserFileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userFile *model.UserFile
func (_e *MockUserFileRepository_Expecter) Update(ctx interface{}, userFile interface{}) *MockUserFileRepository_Update_Call {
	return &MockUserFileRepository_Update_Call{Call: _e.mock.On("Update", ctx, userFile)}
}

func (_c *MockUserFileRepository_Update_Call) Run(run func(ctx context.Context, userFile *model.UserFile)) *MockUserFileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserFile))
	})
	return _c
}

func (_c *MockUserFileRepository_Update_Call) Return(_a0 error) *MockUserFileRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserFileRepository_Update_Call) RunAndReturn(run func(context.Context, *model.UserFile) error) *MockUserFileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserFileRepository creates a new instance of MockUserFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFileRepository {
	mock := &MockUserFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
