// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockUserProfileRepository is an autogenerated mock type for the UserProfileRepository type
type MockUserProfileRepository struct {
	mock.Mock
}

type MockUserProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProfileRepository) EXPECT() *MockUserProfileRepository_Expecter {
	return &MockUserProfileRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, profile
func (_m *MockUserProfileRepository) Create(ctx context.Context, profile *model.UserProfile) (*model.UserProfile, error) {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) (*model.UserProfile, error)); ok {
		return rf(ctx, profile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) *model.UserProfile); ok {
		r0 = rf(ctx, profile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserProfile) error); ok {
		r1 = rf(ctx, profile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserProfileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *model.UserProfile
func (_e *MockUserProfileRepository_Expecter) Create(ctx interface{}, profile interface{}) *MockUserProfileRepository_Create_Call {
	return &MockUserProfileRepository_Create_Call{Call: _e.mock.On("Create", ctx, profile)}
}

func (_c *MockUserProfileRepository_Create_Call) Run(run func(ctx context.Context, profile *model.UserProfile)) *MockUserProfileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserProfile))
	})
	return _c
}

func (_c *MockUserProfileRepository_Create_Call) Return(_a0 *model.UserProfile, _a1 error) *MockUserProfileRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileRepository_Create_Call) RunAndReturn(run func(context.Context, *model.UserProfile) (*model.UserProfile, error)) *MockUserProfileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, profile
func (_m *MockUserProfileRepository) Delete(ctx context.Context, profile *model.UserProfile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserProfileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserProfileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *model.UserProfile
func (_e *MockUserProfileRepository_Expecter) Delete(ctx interface{}, profile interface{}) *MockUserProfileRepository_Delete_Call {
	return &MockUserProfileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, profile)}
}

func (_c *MockUserProfileRepository_Delete_Call) Run(run func(ctx context.Context, profile *model.UserProfile)) *MockUserProfileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserProfile))
	})
	return _c
}

func (_c *MockUserProfileRepository_Delete_Call) Return(_a0 error) *MockUserProfileRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserProfileRepository_Delete_Call) RunAndReturn(run func(context.Context, *model.UserProfile) error) *MockUserProfileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, id
func (_m *MockUserProfileRepository) GetByUserID(ctx context.Context, id int64) (*model.UserProfile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.UserProfile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.UserProfile); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockUserProfileRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserProfileRepository_Expecter) GetByUserID(ctx interface{}, id interface{}) *MockUserProfileRepository_GetByUserID_Call {
	return &MockUserProfileRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, id)}
}

func (_c *MockUserProfileRepository_GetByUserID_Call) Run(run func(ctx context.Context, id int64)) *MockUserProfileRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserProfileRepository_GetByUserID_Call) Return(_a0 *model.UserProfile, _a1 error) *MockUserProfileRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int64) (*model.UserProfile, error)) *MockUserProfileRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockUserProfileRepository) List(ctx context.Context, pagination *param.PaginationParam, filter *param.UserProfileListFilterParam) (*model.UserProfiles, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.UserProfiles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserProfileListFilterParam) (*model.UserProfiles, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserProfileListFilterParam) *model.UserProfiles); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserProfiles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.UserProfileListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserProfileRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.UserProfileListFilterParam
func (_e *MockUserProfileRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockUserProfileRepository_List_Call {
	return &MockUserProfileRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockUserProfileRepository_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.UserProfileListFilterParam)) *MockUserProfileRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.UserProfileListFilterParam))
	})
	return _c
}

func (_c *MockUserProfileRepository_List_Call) Return(_a0 *model.UserProfiles, _a1 error) *MockUserProfileRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileRepository_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.UserProfileListFilterParam) (*model.UserProfiles, error)) *MockUserProfileRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, profile
func (_m *MockUserProfileRepository) Update(ctx context.Context, profile *model.UserProfile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserProfileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserProfileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *model.UserProfile
func (_e *MockUserProfileRepository_Expecter) Update(ctx interface{}, profile interface{}) *MockUserProfileRepository_Update_Call {
	return &MockUserProfileRepository_Update_Call{Call: _e.mock.On("Update", ctx, profile)}
}

func (_c *MockUserProfileRepository_Update_Call) Run(run func(ctx context.Context, profile *model.UserProfile)) *MockUserProfileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserProfile))
	})
	return _c
}

func (_c *MockUserProfileRepository_Update_Call) Return(_a0 error) *MockUserProfileRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserProfileRepository_Update_Call) RunAndReturn(run func(context.Context, *model.UserProfile) error) *MockUserProfileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProfileRepository creates a new instance of MockUserProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProfileRepository {
	mock := &MockUserProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
