// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	params "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockUserDeviceRepository is an autogenerated mock type for the UserDeviceRepository type
type MockUserDeviceRepository struct {
	mock.Mock
}

type MockUserDeviceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDeviceRepository) EXPECT() *MockUserDeviceRepository_Expecter {
	return &MockUserDeviceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, device
func (_m *MockUserDeviceRepository) Create(ctx context.Context, device *model.UserDevice) (*model.UserDevice, error) {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserDevice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserDevice) (*model.UserDevice, error)); ok {
		return rf(ctx, device)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserDevice) *model.UserDevice); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserDevice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserDevice) error); ok {
		r1 = rf(ctx, device)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserDeviceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserDeviceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.UserDevice
func (_e *MockUserDeviceRepository_Expecter) Create(ctx interface{}, device interface{}) *MockUserDeviceRepository_Create_Call {
	return &MockUserDeviceRepository_Create_Call{Call: _e.mock.On("Create", ctx, device)}
}

func (_c *MockUserDeviceRepository_Create_Call) Run(run func(ctx context.Context, device *model.UserDevice)) *MockUserDeviceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserDevice))
	})
	return _c
}

func (_c *MockUserDeviceRepository_Create_Call) Return(_a0 *model.UserDevice, _a1 error) *MockUserDeviceRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserDeviceRepository_Create_Call) RunAndReturn(run func(context.Context, *model.UserDevice) (*model.UserDevice, error)) *MockUserDeviceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, device
func (_m *MockUserDeviceRepository) Delete(ctx context.Context, device *model.UserDevice) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserDevice) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserDeviceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserDeviceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.UserDevice
func (_e *MockUserDeviceRepository_Expecter) Delete(ctx interface{}, device interface{}) *MockUserDeviceRepository_Delete_Call {
	return &MockUserDeviceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, device)}
}

func (_c *MockUserDeviceRepository_Delete_Call) Run(run func(ctx context.Context, device *model.UserDevice)) *MockUserDeviceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserDevice))
	})
	return _c
}

func (_c *MockUserDeviceRepository_Delete_Call) Return(_a0 error) *MockUserDeviceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserDeviceRepository_Delete_Call) RunAndReturn(run func(context.Context, *model.UserDevice) error) *MockUserDeviceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserIDAndDeviceID provides a mock function with given fields: ctx, userID, deviceID
func (_m *MockUserDeviceRepository) GetByUserIDAndDeviceID(ctx context.Context, userID int64, deviceID int64) (*model.UserDevice, error) {
	ret := _m.Called(ctx, userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDAndDeviceID")
	}

	var r0 *model.UserDevice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*model.UserDevice, error)); ok {
		return rf(ctx, userID, deviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *model.UserDevice); ok {
		r0 = rf(ctx, userID, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserDevice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserDeviceRepository_GetByUserIDAndDeviceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserIDAndDeviceID'
type MockUserDeviceRepository_GetByUserIDAndDeviceID_Call struct {
	*mock.Call
}

// GetByUserIDAndDeviceID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - deviceID int64
func (_e *MockUserDeviceRepository_Expecter) GetByUserIDAndDeviceID(ctx interface{}, userID interface{}, deviceID interface{}) *MockUserDeviceRepository_GetByUserIDAndDeviceID_Call {
	return &MockUserDeviceRepository_GetByUserIDAndDeviceID_Call{Call: _e.mock.On("GetByUserIDAndDeviceID", ctx, userID, deviceID)}
}

func (_c *MockUserDeviceRepository_GetByUserIDAndDeviceID_Call) Run(run func(ctx context.Context, userID int64, deviceID int64)) *MockUserDeviceRepository_GetByUserIDAndDeviceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockUserDeviceRepository_GetByUserIDAndDeviceID_Call) Return(_a0 *model.UserDevice, _a1 error) *MockUserDeviceRepository_GetByUserIDAndDeviceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserDeviceRepository_GetByUserIDAndDeviceID_Call) RunAndReturn(run func(context.Context, int64, int64) (*model.UserDevice, error)) *MockUserDeviceRepository_GetByUserIDAndDeviceID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockUserDeviceRepository) List(ctx context.Context, pagination *params.PaginationParam, filter *params.UserDeviceListFilterParam) (*model.UserDevices, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.UserDevices
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *params.PaginationParam, *params.UserDeviceListFilterParam) (*model.UserDevices, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *params.PaginationParam, *params.UserDeviceListFilterParam) *model.UserDevices); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserDevices)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *params.PaginationParam, *params.UserDeviceListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserDeviceRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserDeviceRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *params.PaginationParam
//   - filter *params.UserDeviceListFilterParam
func (_e *MockUserDeviceRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockUserDeviceRepository_List_Call {
	return &MockUserDeviceRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockUserDeviceRepository_List_Call) Run(run func(ctx context.Context, pagination *params.PaginationParam, filter *params.UserDeviceListFilterParam)) *MockUserDeviceRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*params.PaginationParam), args[2].(*params.UserDeviceListFilterParam))
	})
	return _c
}

func (_c *MockUserDeviceRepository_List_Call) Return(_a0 *model.UserDevices, _a1 error) *MockUserDeviceRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserDeviceRepository_List_Call) RunAndReturn(run func(context.Context, *params.PaginationParam, *params.UserDeviceListFilterParam) (*model.UserDevices, error)) *MockUserDeviceRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, userID, deviceID
func (_m *MockUserDeviceRepository) Revoke(ctx context.Context, userID int64, deviceID int64) error {
	ret := _m.Called(ctx, userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserDeviceRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockUserDeviceRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - deviceID int64
func (_e *MockUserDeviceRepository_Expecter) Revoke(ctx interface{}, userID interface{}, deviceID interface{}) *MockUserDeviceRepository_Revoke_Call {
	return &MockUserDeviceRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, userID, deviceID)}
}

func (_c *MockUserDeviceRepository_Revoke_Call) Run(run func(ctx context.Context, userID int64, deviceID int64)) *MockUserDeviceRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockUserDeviceRepository_Revoke_Call) Return(_a0 error) *MockUserDeviceRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserDeviceRepository_Revoke_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockUserDeviceRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, device
func (_m *MockUserDeviceRepository) Update(ctx context.Context, device *model.UserDevice) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserDevice) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserDeviceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserDeviceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.UserDevice
func (_e *MockUserDeviceRepository_Expecter) Update(ctx interface{}, device interface{}) *MockUserDeviceRepository_Update_Call {
	return &MockUserDeviceRepository_Update_Call{Call: _e.mock.On("Update", ctx, device)}
}

func (_c *MockUserDeviceRepository_Update_Call) Run(run func(ctx context.Context, device *model.UserDevice)) *MockUserDeviceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserDevice))
	})
	return _c
}

func (_c *MockUserDeviceRepository_Update_Call) Return(_a0 error) *MockUserDeviceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserDeviceRepository_Update_Call) RunAndReturn(run func(context.Context, *model.UserDevice) error) *MockUserDeviceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionID provides a mock function with given fields: ctx, userID, deviceID, sessionID
func (_m *MockUserDeviceRepository) UpdateSessionID(ctx context.Context, userID int64, deviceID int64, sessionID string) error {
	ret := _m.Called(ctx, userID, deviceID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = rf(ctx, userID, deviceID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserDeviceRepository_UpdateSessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionID'
type MockUserDeviceRepository_UpdateSessionID_Call struct {
	*mock.Call
}

// UpdateSessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - deviceID int64
//   - sessionID string
func (_e *MockUserDeviceRepository_Expecter) UpdateSessionID(ctx interface{}, userID interface{}, deviceID interface{}, sessionID interface{}) *MockUserDeviceRepository_UpdateSessionID_Call {
	return &MockUserDeviceRepository_UpdateSessionID_Call{Call: _e.mock.On("UpdateSessionID", ctx, userID, deviceID, sessionID)}
}

func (_c *MockUserDeviceRepository_UpdateSessionID_Call) Run(run func(ctx context.Context, userID int64, deviceID int64, sessionID string)) *MockUserDeviceRepository_UpdateSessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockUserDeviceRepository_UpdateSessionID_Call) Return(_a0 error) *MockUserDeviceRepository_UpdateSessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserDeviceRepository_UpdateSessionID_Call) RunAndReturn(run func(context.Context, int64, int64, string) error) *MockUserDeviceRepository_UpdateSessionID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserDeviceRepository creates a new instance of MockUserDeviceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDeviceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDeviceRepository {
	mock := &MockUserDeviceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
