// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserFileResolver is an autogenerated mock type for the UserFileResolver type
type MockUserFileResolver struct {
	mock.Mock
}

type MockUserFileResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFileResolver) EXPECT() *MockUserFileResolver_Expecter {
	return &MockUserFileResolver_Expecter{mock: &_m.Mock}
}

// IDsByUIDs provides a mock function with given fields: ctx, userFileUIDs
func (_m *MockUserFileResolver) IDsByUIDs(ctx context.Context, userFileUIDs []string) (map[string]int64, error) {
	ret := _m.Called(ctx, userFileUIDs)

	if len(ret) == 0 {
		panic("no return value specified for IDsByUIDs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, userFileUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, userFileUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, userFileUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileResolver_IDsByUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByUIDs'
type MockUserFileResolver_IDsByUIDs_Call struct {
	*mock.Call
}

// IDsByUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userFileUIDs []string
func (_e *MockUserFileResolver_Expecter) IDsByUIDs(ctx interface{}, userFileUIDs interface{}) *MockUserFileResolver_IDsByUIDs_Call {
	return &MockUserFileResolver_IDsByUIDs_Call{Call: _e.mock.On("IDsByUIDs", ctx, userFileUIDs)}
}

func (_c *MockUserFileResolver_IDsByUIDs_Call) Run(run func(ctx context.Context, userFileUIDs []string)) *MockUserFileResolver_IDsByUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockUserFileResolver_IDsByUIDs_Call) Return(_a0 map[string]int64, _a1 error) *MockUserFileResolver_IDsByUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileResolver_IDsByUIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockUserFileResolver_IDsByUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UIDsByIDs provides a mock function with given fields: ctx, userFileIDs
func (_m *MockUserFileResolver) UIDsByIDs(ctx context.Context, userFileIDs []int64) (map[int64]string, error) {
	ret := _m.Called(ctx, userFileIDs)

	if len(ret) == 0 {
		panic("no return value specified for UIDsByIDs")
	}

	var r0 map[int64]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]string, error)); ok {
		return rf(ctx, userFileIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]string); ok {
		r0 = rf(ctx, userFileIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, userFileIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileResolver_UIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDsByIDs'
type MockUserFileResolver_UIDsByIDs_Call struct {
	*mock.Call
}

// UIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userFileIDs []int64
func (_e *MockUserFileResolver_Expecter) UIDsByIDs(ctx interface{}, userFileIDs interface{}) *MockUserFileResolver_UIDsByIDs_Call {
	return &MockUserFileResolver_UIDsByIDs_Call{Call: _e.mock.On("UIDsByIDs", ctx, userFileIDs)}
}

func (_c *MockUserFileResolver_UIDsByIDs_Call) Run(run func(ctx context.Context, userFileIDs []int64)) *MockUserFileResolver_UIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockUserFileResolver_UIDsByIDs_Call) Return(_a0 map[int64]string, _a1 error) *MockUserFileResolver_UIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileResolver_UIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]string, error)) *MockUserFileResolver_UIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserFileResolver creates a new instance of MockUserFileResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFileResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFileResolver {
	mock := &MockUserFileResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
