// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	signal "github.com/adityakw90/service-user/internal/core/domain/signal"
)

// MockServiceObserver is an autogenerated mock type for the ServiceObserver type
type MockServiceObserver[T interface{}] struct {
	mock.Mock
}

type MockServiceObserver_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockServiceObserver[T]) EXPECT() *MockServiceObserver_Expecter[T] {
	return &MockServiceObserver_Expecter[T]{mock: &_m.Mock}
}

// DetachContext provides a mock function with given fields: ctx
func (_m *MockServiceObserver[T]) DetachContext(ctx context.Context) (context.Context, func()) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DetachContext")
	}

	var r0 context.Context
	var r1 func()
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, func())); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) func()); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	return r0, r1
}

// MockServiceObserver_DetachContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachContext'
type MockServiceObserver_DetachContext_Call[T interface{}] struct {
	*mock.Call
}

// DetachContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceObserver_Expecter[T]) DetachContext(ctx interface{}) *MockServiceObserver_DetachContext_Call[T] {
	return &MockServiceObserver_DetachContext_Call[T]{Call: _e.mock.On("DetachContext", ctx)}
}

func (_c *MockServiceObserver_DetachContext_Call[T]) Run(run func(ctx context.Context)) *MockServiceObserver_DetachContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceObserver_DetachContext_Call[T]) Return(_a0 context.Context, _a1 func()) *MockServiceObserver_DetachContext_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceObserver_DetachContext_Call[T]) RunAndReturn(run func(context.Context) (context.Context, func())) *MockServiceObserver_DetachContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// OnSignal provides a mock function with given fields: ctx, _a1, data, err
func (_m *MockServiceObserver[T]) OnSignal(ctx context.Context, _a1 signal.SignalType, data T, err error) {
	_m.Called(ctx, _a1, data, err)
}

// MockServiceObserver_OnSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnSignal'
type MockServiceObserver_OnSignal_Call[T interface{}] struct {
	*mock.Call
}

// OnSignal is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 signal.SignalType
//   - data T
//   - err error
func (_e *MockServiceObserver_Expecter[T]) OnSignal(ctx interface{}, _a1 interface{}, data interface{}, err interface{}) *MockServiceObserver_OnSignal_Call[T] {
	return &MockServiceObserver_OnSignal_Call[T]{Call: _e.mock.On("OnSignal", ctx, _a1, data, err)}
}

func (_c *MockServiceObserver_OnSignal_Call[T]) Run(run func(ctx context.Context, _a1 signal.SignalType, data T, err error)) *MockServiceObserver_OnSignal_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(signal.SignalType), args[2].(T), args[3].(error))
	})
	return _c
}

func (_c *MockServiceObserver_OnSignal_Call[T]) Return() *MockServiceObserver_OnSignal_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceObserver_OnSignal_Call[T]) RunAndReturn(run func(context.Context, signal.SignalType, T, error)) *MockServiceObserver_OnSignal_Call[T] {
	_c.Run(run)
	return _c
}

// NewMockServiceObserver creates a new instance of MockServiceObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceObserver[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceObserver[T] {
	mock := &MockServiceObserver[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
