// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserCache is an autogenerated mock type for the UserCache type
type MockUserCache struct {
	mock.Mock
}

type MockUserCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCache) EXPECT() *MockUserCache_Expecter {
	return &MockUserCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, uid, fallback
func (_m *MockUserCache) Get(ctx context.Context, uid string, fallback func(context.Context, string) (*model.User, error)) (*model.User, error) {
	ret := _m.Called(ctx, uid, fallback)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context, string) (*model.User, error)) (*model.User, error)); ok {
		return rf(ctx, uid, fallback)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context, string) (*model.User, error)) *model.User); ok {
		r0 = rf(ctx, uid, fallback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, func(context.Context, string) (*model.User, error)) error); ok {
		r1 = rf(ctx, uid, fallback)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - fallback func(context.Context , string)(*model.User , error)
func (_e *MockUserCache_Expecter) Get(ctx interface{}, uid interface{}, fallback interface{}) *MockUserCache_Get_Call {
	return &MockUserCache_Get_Call{Call: _e.mock.On("Get", ctx, uid, fallback)}
}

func (_c *MockUserCache_Get_Call) Run(run func(ctx context.Context, uid string, fallback func(context.Context, string) (*model.User, error))) *MockUserCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context, string) (*model.User, error)))
	})
	return _c
}

func (_c *MockUserCache_Get_Call) Return(_a0 *model.User, _a1 error) *MockUserCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserCache_Get_Call) RunAndReturn(run func(context.Context, string, func(context.Context, string) (*model.User, error)) (*model.User, error)) *MockUserCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserCache creates a new instance of MockUserCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCache {
	mock := &MockUserCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
