// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOAuthProvider is an autogenerated mock type for the OAuthProvider type
type MockOAuthProvider struct {
	mock.Mock
}

type MockOAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthProvider) EXPECT() *MockOAuthProvider_Expecter {
	return &MockOAuthProvider_Expecter{mock: &_m.Mock}
}

// ExchangeCode provides a mock function with given fields: ctx, code, state, redirectURI
func (_m *MockOAuthProvider) ExchangeCode(ctx context.Context, code string, state string, redirectURI string) (*model.OAuthTokens, error) {
	ret := _m.Called(ctx, code, state, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 *model.OAuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.OAuthTokens, error)); ok {
		return rf(ctx, code, state, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.OAuthTokens); ok {
		r0 = rf(ctx, code, state, redirectURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OAuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, code, state, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthProvider_ExchangeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCode'
type MockOAuthProvider_ExchangeCode_Call struct {
	*mock.Call
}

// ExchangeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - state string
//   - redirectURI string
func (_e *MockOAuthProvider_Expecter) ExchangeCode(ctx interface{}, code interface{}, state interface{}, redirectURI interface{}) *MockOAuthProvider_ExchangeCode_Call {
	return &MockOAuthProvider_ExchangeCode_Call{Call: _e.mock.On("ExchangeCode", ctx, code, state, redirectURI)}
}

func (_c *MockOAuthProvider_ExchangeCode_Call) Run(run func(ctx context.Context, code string, state string, redirectURI string)) *MockOAuthProvider_ExchangeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockOAuthProvider_ExchangeCode_Call) Return(_a0 *model.OAuthTokens, _a1 error) *MockOAuthProvider_ExchangeCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthProvider_ExchangeCode_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.OAuthTokens, error)) *MockOAuthProvider_ExchangeCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationURL provides a mock function with given fields: ctx, redirectURI, state
func (_m *MockOAuthProvider) GetAuthorizationURL(ctx context.Context, redirectURI string, state string) (string, error) {
	ret := _m.Called(ctx, redirectURI, state)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, redirectURI, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, redirectURI, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, redirectURI, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthProvider_GetAuthorizationURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationURL'
type MockOAuthProvider_GetAuthorizationURL_Call struct {
	*mock.Call
}

// GetAuthorizationURL is a helper method to define mock.On call
//   - ctx context.Context
//   - redirectURI string
//   - state string
func (_e *MockOAuthProvider_Expecter) GetAuthorizationURL(ctx interface{}, redirectURI interface{}, state interface{}) *MockOAuthProvider_GetAuthorizationURL_Call {
	return &MockOAuthProvider_GetAuthorizationURL_Call{Call: _e.mock.On("GetAuthorizationURL", ctx, redirectURI, state)}
}

func (_c *MockOAuthProvider_GetAuthorizationURL_Call) Run(run func(ctx context.Context, redirectURI string, state string)) *MockOAuthProvider_GetAuthorizationURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthProvider_GetAuthorizationURL_Call) Return(_a0 string, _a1 error) *MockOAuthProvider_GetAuthorizationURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthProvider_GetAuthorizationURL_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockOAuthProvider_GetAuthorizationURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function with given fields: ctx, token
func (_m *MockOAuthProvider) GetUserInfo(ctx context.Context, token *model.OAuthTokens) (*model.OAuthUserInfo, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *model.OAuthUserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OAuthTokens) (*model.OAuthUserInfo, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.OAuthTokens) *model.OAuthUserInfo); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OAuthUserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.OAuthTokens) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthProvider_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockOAuthProvider_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.OAuthTokens
func (_e *MockOAuthProvider_Expecter) GetUserInfo(ctx interface{}, token interface{}) *MockOAuthProvider_GetUserInfo_Call {
	return &MockOAuthProvider_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, token)}
}

func (_c *MockOAuthProvider_GetUserInfo_Call) Run(run func(ctx context.Context, token *model.OAuthTokens)) *MockOAuthProvider_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.OAuthTokens))
	})
	return _c
}

func (_c *MockOAuthProvider_GetUserInfo_Call) Return(_a0 *model.OAuthUserInfo, _a1 error) *MockOAuthProvider_GetUserInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthProvider_GetUserInfo_Call) RunAndReturn(run func(context.Context, *model.OAuthTokens) (*model.OAuthUserInfo, error)) *MockOAuthProvider_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthProvider creates a new instance of MockOAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthProvider {
	mock := &MockOAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
