// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	params "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockUserFileService is an autogenerated mock type for the UserFileService type
type MockUserFileService struct {
	mock.Mock
}

type MockUserFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFileService) EXPECT() *MockUserFileService_Expecter {
	return &MockUserFileService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, param
func (_m *MockUserFileService) Add(ctx context.Context, param params.UserFileCreateParam) (*model.UserFile, error) {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *model.UserFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, params.UserFileCreateParam) (*model.UserFile, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, params.UserFileCreateParam) *model.UserFile); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, params.UserFileCreateParam) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockUserFileService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - param params.UserFileCreateParam
func (_e *MockUserFileService_Expecter) Add(ctx interface{}, param interface{}) *MockUserFileService_Add_Call {
	return &MockUserFileService_Add_Call{Call: _e.mock.On("Add", ctx, param)}
}

func (_c *MockUserFileService_Add_Call) Run(run func(ctx context.Context, param params.UserFileCreateParam)) *MockUserFileService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(params.UserFileCreateParam))
	})
	return _c
}

func (_c *MockUserFileService_Add_Call) Return(_a0 *model.UserFile, _a1 error) *MockUserFileService_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileService_Add_Call) RunAndReturn(run func(context.Context, params.UserFileCreateParam) (*model.UserFile, error)) *MockUserFileService_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uid
func (_m *MockUserFileService) Delete(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserFileService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserFileService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockUserFileService_Expecter) Delete(ctx interface{}, uid interface{}) *MockUserFileService_Delete_Call {
	return &MockUserFileService_Delete_Call{Call: _e.mock.On("Delete", ctx, uid)}
}

func (_c *MockUserFileService_Delete_Call) Run(run func(ctx context.Context, uid string)) *MockUserFileService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserFileService_Delete_Call) Return(_a0 error) *MockUserFileService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserFileService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockUserFileService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uid
func (_m *MockUserFileService) Get(ctx context.Context, uid string) (*model.UserFile, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserFile, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserFile); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserFileService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockUserFileService_Expecter) Get(ctx interface{}, uid interface{}) *MockUserFileService_Get_Call {
	return &MockUserFileService_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *MockUserFileService_Get_Call) Run(run func(ctx context.Context, uid string)) *MockUserFileService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserFileService_Get_Call) Return(_a0 *model.UserFile, _a1 error) *MockUserFileService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.UserFile, error)) *MockUserFileService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockUserFileService) List(ctx context.Context, pagination *params.PaginationParam, filter *params.UserFileListFilterParam) (*model.UserFiles, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.UserFiles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *params.PaginationParam, *params.UserFileListFilterParam) (*model.UserFiles, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *params.PaginationParam, *params.UserFileListFilterParam) *model.UserFiles); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFiles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *params.PaginationParam, *params.UserFileListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFileService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserFileService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *params.PaginationParam
//   - filter *params.UserFileListFilterParam
func (_e *MockUserFileService_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockUserFileService_List_Call {
	return &MockUserFileService_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockUserFileService_List_Call) Run(run func(ctx context.Context, pagination *params.PaginationParam, filter *params.UserFileListFilterParam)) *MockUserFileService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*params.PaginationParam), args[2].(*params.UserFileListFilterParam))
	})
	return _c
}

func (_c *MockUserFileService_List_Call) Return(_a0 *model.UserFiles, _a1 error) *MockUserFileService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFileService_List_Call) RunAndReturn(run func(context.Context, *params.PaginationParam, *params.UserFileListFilterParam) (*model.UserFiles, error)) *MockUserFileService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uid, param
func (_m *MockUserFileService) Update(ctx context.Context, uid string, param params.UserFileUpdateParam) error {
	ret := _m.Called(ctx, uid, param)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, params.UserFileUpdateParam) error); ok {
		r0 = rf(ctx, uid, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserFileService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserFileService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - param params.UserFileUpdateParam
func (_e *MockUserFileService_Expecter) Update(ctx interface{}, uid interface{}, param interface{}) *MockUserFileService_Update_Call {
	return &MockUserFileService_Update_Call{Call: _e.mock.On("Update", ctx, uid, param)}
}

func (_c *MockUserFileService_Update_Call) Run(run func(ctx context.Context, uid string, param params.UserFileUpdateParam)) *MockUserFileService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(params.UserFileUpdateParam))
	})
	return _c
}

func (_c *MockUserFileService_Update_Call) Return(_a0 error) *MockUserFileService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserFileService_Update_Call) RunAndReturn(run func(context.Context, string, params.UserFileUpdateParam) error) *MockUserFileService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserFileService creates a new instance of MockUserFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFileService {
	mock := &MockUserFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
