// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userUID, _a2
func (_m *MockUserService) ChangePassword(ctx context.Context, userUID string, _a2 *param.UserChangePasswordParam) error {
	ret := _m.Called(ctx, userUID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.UserChangePasswordParam) error); ok {
		r0 = rf(ctx, userUID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
//   - _a2 *param.UserChangePasswordParam
func (_e *MockUserService_Expecter) ChangePassword(ctx interface{}, userUID interface{}, _a2 interface{}) *MockUserService_ChangePassword_Call {
	return &MockUserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userUID, _a2)}
}

func (_c *MockUserService_ChangePassword_Call) Run(run func(ctx context.Context, userUID string, _a2 *param.UserChangePasswordParam)) *MockUserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*param.UserChangePasswordParam))
	})
	return _c
}

func (_c *MockUserService_ChangePassword_Call) Return(_a0 error) *MockUserService_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_ChangePassword_Call) RunAndReturn(run func(context.Context, string, *param.UserChangePasswordParam) error) *MockUserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockUserService) Create(ctx context.Context, _a1 *param.UserCreateParam) (*model.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.UserCreateParam) (*model.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.UserCreateParam) *model.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.UserCreateParam) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *param.UserCreateParam
func (_e *MockUserService_Expecter) Create(ctx interface{}, _a1 interface{}) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockUserService_Create_Call) Run(run func(ctx context.Context, _a1 *param.UserCreateParam)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.UserCreateParam))
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(_a0 *model.User, _a1 error) *MockUserService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(context.Context, *param.UserCreateParam) (*model.User, error)) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uid
func (_m *MockUserService) Delete(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockUserService_Expecter) Delete(ctx interface{}, uid interface{}) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, uid)}
}

func (_c *MockUserService_Delete_Call) Run(run func(ctx context.Context, uid string)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(_a0 error) *MockUserService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uid
func (_m *MockUserService) Get(ctx context.Context, uid string) (*model.User, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockUserService_Expecter) Get(ctx interface{}, uid interface{}) *MockUserService_Get_Call {
	return &MockUserService_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *MockUserService_Get_Call) Run(run func(ctx context.Context, uid string)) *MockUserService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_Get_Call) Return(_a0 *model.User, _a1 error) *MockUserService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, userUID
func (_m *MockUserService) GetProfile(ctx context.Context, userUID string) (*model.UserProfile, error) {
	ret := _m.Called(ctx, userUID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *model.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserProfile, error)); ok {
		return rf(ctx, userUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserProfile); ok {
		r0 = rf(ctx, userUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockUserService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
func (_e *MockUserService_Expecter) GetProfile(ctx interface{}, userUID interface{}) *MockUserService_GetProfile_Call {
	return &MockUserService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userUID)}
}

func (_c *MockUserService_GetProfile_Call) Run(run func(ctx context.Context, userUID string)) *MockUserService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetProfile_Call) Return(_a0 *model.UserProfile, _a1 error) *MockUserService_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetProfile_Call) RunAndReturn(run func(context.Context, string) (*model.UserProfile, error)) *MockUserService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockUserService) List(ctx context.Context, pagination *param.PaginationParam, filter *param.UserListFilterParam) (*model.Users, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserListFilterParam) (*model.Users, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserListFilterParam) *model.Users); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Users)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.UserListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.UserListFilterParam
func (_e *MockUserService_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockUserService_List_Call {
	return &MockUserService_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockUserService_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.UserListFilterParam)) *MockUserService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.UserListFilterParam))
	})
	return _c
}

func (_c *MockUserService_List_Call) Return(_a0 *model.Users, _a1 error) *MockUserService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.UserListFilterParam) (*model.Users, error)) *MockUserService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListDevice provides a mock function with given fields: ctx, userUID, pagination, filter
func (_m *MockUserService) ListDevice(ctx context.Context, userUID string, pagination *param.PaginationParam, filter *param.UserDeviceListFilterParam) (*model.Devices, error) {
	ret := _m.Called(ctx, userUID, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListDevice")
	}

	var r0 *model.Devices
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.PaginationParam, *param.UserDeviceListFilterParam) (*model.Devices, error)); ok {
		return rf(ctx, userUID, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.PaginationParam, *param.UserDeviceListFilterParam) *model.Devices); ok {
		r0 = rf(ctx, userUID, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Devices)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *param.PaginationParam, *param.UserDeviceListFilterParam) error); ok {
		r1 = rf(ctx, userUID, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_ListDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevice'
type MockUserService_ListDevice_Call struct {
	*mock.Call
}

// ListDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
//   - pagination *param.PaginationParam
//   - filter *param.UserDeviceListFilterParam
func (_e *MockUserService_Expecter) ListDevice(ctx interface{}, userUID interface{}, pagination interface{}, filter interface{}) *MockUserService_ListDevice_Call {
	return &MockUserService_ListDevice_Call{Call: _e.mock.On("ListDevice", ctx, userUID, pagination, filter)}
}

func (_c *MockUserService_ListDevice_Call) Run(run func(ctx context.Context, userUID string, pagination *param.PaginationParam, filter *param.UserDeviceListFilterParam)) *MockUserService_ListDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*param.PaginationParam), args[3].(*param.UserDeviceListFilterParam))
	})
	return _c
}

func (_c *MockUserService_ListDevice_Call) Return(_a0 *model.Devices, _a1 error) *MockUserService_ListDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_ListDevice_Call) RunAndReturn(run func(context.Context, string, *param.PaginationParam, *param.UserDeviceListFilterParam) (*model.Devices, error)) *MockUserService_ListDevice_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeDevice provides a mock function with given fields: ctx, userUID, deviceUID
func (_m *MockUserService) RevokeDevice(ctx context.Context, userUID string, deviceUID string) error {
	ret := _m.Called(ctx, userUID, deviceUID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userUID, deviceUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_RevokeDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeDevice'
type MockUserService_RevokeDevice_Call struct {
	*mock.Call
}

// RevokeDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
//   - deviceUID string
func (_e *MockUserService_Expecter) RevokeDevice(ctx interface{}, userUID interface{}, deviceUID interface{}) *MockUserService_RevokeDevice_Call {
	return &MockUserService_RevokeDevice_Call{Call: _e.mock.On("RevokeDevice", ctx, userUID, deviceUID)}
}

func (_c *MockUserService_RevokeDevice_Call) Run(run func(ctx context.Context, userUID string, deviceUID string)) *MockUserService_RevokeDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_RevokeDevice_Call) Return(_a0 error) *MockUserService_RevokeDevice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_RevokeDevice_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserService_RevokeDevice_Call {
	_c.Call.Return(run)
	return _c
}

// SetPin provides a mock function with given fields: ctx, userUID, pin
func (_m *MockUserService) SetPin(ctx context.Context, userUID string, pin string) error {
	ret := _m.Called(ctx, userUID, pin)

	if len(ret) == 0 {
		panic("no return value specified for SetPin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userUID, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_SetPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPin'
type MockUserService_SetPin_Call struct {
	*mock.Call
}

// SetPin is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
//   - pin string
func (_e *MockUserService_Expecter) SetPin(ctx interface{}, userUID interface{}, pin interface{}) *MockUserService_SetPin_Call {
	return &MockUserService_SetPin_Call{Call: _e.mock.On("SetPin", ctx, userUID, pin)}
}

func (_c *MockUserService_SetPin_Call) Run(run func(ctx context.Context, userUID string, pin string)) *MockUserService_SetPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_SetPin_Call) Return(_a0 error) *MockUserService_SetPin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_SetPin_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserService_SetPin_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uid, _a2
func (_m *MockUserService) Update(ctx context.Context, uid string, _a2 *param.UserUpdateParam) error {
	ret := _m.Called(ctx, uid, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.UserUpdateParam) error); ok {
		r0 = rf(ctx, uid, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - _a2 *param.UserUpdateParam
func (_e *MockUserService_Expecter) Update(ctx interface{}, uid interface{}, _a2 interface{}) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", ctx, uid, _a2)}
}

func (_c *MockUserService_Update_Call) Run(run func(ctx context.Context, uid string, _a2 *param.UserUpdateParam)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*param.UserUpdateParam))
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(_a0 error) *MockUserService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(context.Context, string, *param.UserUpdateParam) error) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userUID, opts
func (_m *MockUserService) UpdateProfile(ctx context.Context, userUID string, opts param.UserProfileUpdateParam) error {
	ret := _m.Called(ctx, userUID, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, param.UserProfileUpdateParam) error); ok {
		r0 = rf(ctx, userUID, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
//   - opts param.UserProfileUpdateParam
func (_e *MockUserService_Expecter) UpdateProfile(ctx interface{}, userUID interface{}, opts interface{}) *MockUserService_UpdateProfile_Call {
	return &MockUserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userUID, opts)}
}

func (_c *MockUserService_UpdateProfile_Call) Run(run func(ctx context.Context, userUID string, opts param.UserProfileUpdateParam)) *MockUserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(param.UserProfileUpdateParam))
	})
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) Return(_a0 error) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, param.UserProfileUpdateParam) error) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
