// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, payload
func (_m *MockAuthService) Authenticate(ctx context.Context, payload *param.AuthParams) (*model.Token, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.AuthParams) (*model.Token, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.AuthParams) *model.Token); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.AuthParams) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *param.AuthParams
func (_e *MockAuthService_Expecter) Authenticate(ctx interface{}, payload interface{}) *MockAuthService_Authenticate_Call {
	return &MockAuthService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, payload)}
}

func (_c *MockAuthService_Authenticate_Call) Run(run func(ctx context.Context, payload *param.AuthParams)) *MockAuthService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.AuthParams))
	})
	return _c
}

func (_c *MockAuthService_Authenticate_Call) Return(_a0 *model.Token, _a1 error) *MockAuthService_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Authenticate_Call) RunAndReturn(run func(context.Context, *param.AuthParams) (*model.Token, error)) *MockAuthService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GoogleOAuth provides a mock function with given fields: ctx, redirectURI
func (_m *MockAuthService) GoogleOAuth(ctx context.Context, redirectURI string) (string, string, error) {
	ret := _m.Called(ctx, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for GoogleOAuth")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, redirectURI)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, redirectURI)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, redirectURI)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_GoogleOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GoogleOAuth'
type MockAuthService_GoogleOAuth_Call struct {
	*mock.Call
}

// GoogleOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - redirectURI string
func (_e *MockAuthService_Expecter) GoogleOAuth(ctx interface{}, redirectURI interface{}) *MockAuthService_GoogleOAuth_Call {
	return &MockAuthService_GoogleOAuth_Call{Call: _e.mock.On("GoogleOAuth", ctx, redirectURI)}
}

func (_c *MockAuthService_GoogleOAuth_Call) Run(run func(ctx context.Context, redirectURI string)) *MockAuthService_GoogleOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_GoogleOAuth_Call) Return(_a0 string, _a1 string, _a2 error) *MockAuthService_GoogleOAuth_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthService_GoogleOAuth_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *MockAuthService_GoogleOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// HandleGoogleOAuth provides a mock function with given fields: ctx, code, state, redirectURI
func (_m *MockAuthService) HandleGoogleOAuth(ctx context.Context, code string, state string, redirectURI string) (*model.Token, error) {
	ret := _m.Called(ctx, code, state, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for HandleGoogleOAuth")
	}

	var r0 *model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Token, error)); ok {
		return rf(ctx, code, state, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Token); ok {
		r0 = rf(ctx, code, state, redirectURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, code, state, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_HandleGoogleOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleGoogleOAuth'
type MockAuthService_HandleGoogleOAuth_Call struct {
	*mock.Call
}

// HandleGoogleOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - state string
//   - redirectURI string
func (_e *MockAuthService_Expecter) HandleGoogleOAuth(ctx interface{}, code interface{}, state interface{}, redirectURI interface{}) *MockAuthService_HandleGoogleOAuth_Call {
	return &MockAuthService_HandleGoogleOAuth_Call{Call: _e.mock.On("HandleGoogleOAuth", ctx, code, state, redirectURI)}
}

func (_c *MockAuthService_HandleGoogleOAuth_Call) Run(run func(ctx context.Context, code string, state string, redirectURI string)) *MockAuthService_HandleGoogleOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_HandleGoogleOAuth_Call) Return(_a0 *model.Token, _a1 error) *MockAuthService_HandleGoogleOAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_HandleGoogleOAuth_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.Token, error)) *MockAuthService_HandleGoogleOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthService) RefreshToken(ctx context.Context, refreshToken string) (*model.Token, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Token, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Token); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(_a0 *model.Token, _a1 error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (*model.Token, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function with given fields: ctx, token, tokenType
func (_m *MockAuthService) RevokeToken(ctx context.Context, token string, tokenType string) error {
	ret := _m.Called(ctx, token, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, tokenType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockAuthService_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - tokenType string
func (_e *MockAuthService_Expecter) RevokeToken(ctx interface{}, token interface{}, tokenType interface{}) *MockAuthService_RevokeToken_Call {
	return &MockAuthService_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, token, tokenType)}
}

func (_c *MockAuthService_RevokeToken_Call) Run(run func(ctx context.Context, token string, tokenType string)) *MockAuthService_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_RevokeToken_Call) Return(_a0 error) *MockAuthService_RevokeToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_RevokeToken_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAuthService_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: ctx, accessToken
func (_m *MockAuthService) ValidateToken(ctx context.Context, accessToken string) (*model.TokenClaims, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *model.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.TokenClaims, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.TokenClaims); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockAuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockAuthService_Expecter) ValidateToken(ctx interface{}, accessToken interface{}) *MockAuthService_ValidateToken_Call {
	return &MockAuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, accessToken)}
}

func (_c *MockAuthService_ValidateToken_Call) Run(run func(ctx context.Context, accessToken string)) *MockAuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) Return(_a0 *model.TokenClaims, _a1 error) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) RunAndReturn(run func(context.Context, string) (*model.TokenClaims, error)) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPin provides a mock function with given fields: ctx, userUid, pin
func (_m *MockAuthService) VerifyPin(ctx context.Context, userUid string, pin string) (bool, error) {
	ret := _m.Called(ctx, userUid, pin)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPin")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userUid, pin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userUid, pin)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userUid, pin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_VerifyPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPin'
type MockAuthService_VerifyPin_Call struct {
	*mock.Call
}

// VerifyPin is a helper method to define mock.On call
//   - ctx context.Context
//   - userUid string
//   - pin string
func (_e *MockAuthService_Expecter) VerifyPin(ctx interface{}, userUid interface{}, pin interface{}) *MockAuthService_VerifyPin_Call {
	return &MockAuthService_VerifyPin_Call{Call: _e.mock.On("VerifyPin", ctx, userUid, pin)}
}

func (_c *MockAuthService_VerifyPin_Call) Run(run func(ctx context.Context, userUid string, pin string)) *MockAuthService_VerifyPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_VerifyPin_Call) Return(_a0 bool, _a1 error) *MockAuthService_VerifyPin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_VerifyPin_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockAuthService_VerifyPin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
