// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockDeviceService is an autogenerated mock type for the DeviceService type
type MockDeviceService struct {
	mock.Mock
}

type MockDeviceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceService) EXPECT() *MockDeviceService_Expecter {
	return &MockDeviceService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, uid
func (_m *MockDeviceService) Delete(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeviceService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockDeviceService_Expecter) Delete(ctx interface{}, uid interface{}) *MockDeviceService_Delete_Call {
	return &MockDeviceService_Delete_Call{Call: _e.mock.On("Delete", ctx, uid)}
}

func (_c *MockDeviceService_Delete_Call) Run(run func(ctx context.Context, uid string)) *MockDeviceService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeviceService_Delete_Call) Return(_a0 error) *MockDeviceService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockDeviceService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uid
func (_m *MockDeviceService) Get(ctx context.Context, uid string) (*model.Device, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Device, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Device); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDeviceService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockDeviceService_Expecter) Get(ctx interface{}, uid interface{}) *MockDeviceService_Get_Call {
	return &MockDeviceService_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *MockDeviceService_Get_Call) Run(run func(ctx context.Context, uid string)) *MockDeviceService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeviceService_Get_Call) Return(_a0 *model.Device, _a1 error) *MockDeviceService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Device, error)) *MockDeviceService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockDeviceService) List(ctx context.Context, pagination *param.PaginationParam, filter *param.DeviceListFilterParam) (*model.Devices, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.Devices
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.DeviceListFilterParam) (*model.Devices, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.DeviceListFilterParam) *model.Devices); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Devices)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.DeviceListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeviceService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.DeviceListFilterParam
func (_e *MockDeviceService_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockDeviceService_List_Call {
	return &MockDeviceService_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockDeviceService_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.DeviceListFilterParam)) *MockDeviceService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.DeviceListFilterParam))
	})
	return _c
}

func (_c *MockDeviceService_List_Call) Return(_a0 *model.Devices, _a1 error) *MockDeviceService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceService_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.DeviceListFilterParam) (*model.Devices, error)) *MockDeviceService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceService creates a new instance of MockDeviceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceService {
	mock := &MockDeviceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
