// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	executor "github.com/adityakw90/service-user/internal/core/port/executor"
	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockExecutor) Close() {
	_m.Called()
}

// MockExecutor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockExecutor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockExecutor_Expecter) Close() *MockExecutor_Close_Call {
	return &MockExecutor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockExecutor_Close_Call) Run(run func()) *MockExecutor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutor_Close_Call) Return() *MockExecutor_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_Close_Call) RunAndReturn(run func()) *MockExecutor_Close_Call {
	_c.Run(run)
	return _c
}

// Do provides a mock function with given fields: ctx, name, fn
func (_m *MockExecutor) Do(ctx context.Context, name string, fn func(context.Context) error) error {
	ret := _m.Called(ctx, name, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) error); ok {
		r0 = rf(ctx, name, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutor_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockExecutor_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - fn func(context.Context) error
func (_e *MockExecutor_Expecter) Do(ctx interface{}, name interface{}, fn interface{}) *MockExecutor_Do_Call {
	return &MockExecutor_Do_Call{Call: _e.mock.On("Do", ctx, name, fn)}
}

func (_c *MockExecutor_Do_Call) Run(run func(ctx context.Context, name string, fn func(context.Context) error)) *MockExecutor_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *MockExecutor_Do_Call) Return(_a0 error) *MockExecutor_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_Do_Call) RunAndReturn(run func(context.Context, string, func(context.Context) error) error) *MockExecutor_Do_Call {
	_c.Call.Return(run)
	return _c
}

// DoAsync provides a mock function with given fields: ctx, name, fn
func (_m *MockExecutor) DoAsync(ctx context.Context, name string, fn func(context.Context) error) error {
	ret := _m.Called(ctx, name, fn)

	if len(ret) == 0 {
		panic("no return value specified for DoAsync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) error); ok {
		r0 = rf(ctx, name, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutor_DoAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoAsync'
type MockExecutor_DoAsync_Call struct {
	*mock.Call
}

// DoAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - fn func(context.Context) error
func (_e *MockExecutor_Expecter) DoAsync(ctx interface{}, name interface{}, fn interface{}) *MockExecutor_DoAsync_Call {
	return &MockExecutor_DoAsync_Call{Call: _e.mock.On("DoAsync", ctx, name, fn)}
}

func (_c *MockExecutor_DoAsync_Call) Run(run func(ctx context.Context, name string, fn func(context.Context) error)) *MockExecutor_DoAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *MockExecutor_DoAsync_Call) Return(_a0 error) *MockExecutor_DoAsync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_DoAsync_Call) RunAndReturn(run func(context.Context, string, func(context.Context) error) error) *MockExecutor_DoAsync_Call {
	_c.Call.Return(run)
	return _c
}

// DoParallel provides a mock function with given fields: ctx, name, tasks
func (_m *MockExecutor) DoParallel(ctx context.Context, name string, tasks []executor.Task) error {
	ret := _m.Called(ctx, name, tasks)

	if len(ret) == 0 {
		panic("no return value specified for DoParallel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []executor.Task) error); ok {
		r0 = rf(ctx, name, tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutor_DoParallel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoParallel'
type MockExecutor_DoParallel_Call struct {
	*mock.Call
}

// DoParallel is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - tasks []executor.Task
func (_e *MockExecutor_Expecter) DoParallel(ctx interface{}, name interface{}, tasks interface{}) *MockExecutor_DoParallel_Call {
	return &MockExecutor_DoParallel_Call{Call: _e.mock.On("DoParallel", ctx, name, tasks)}
}

func (_c *MockExecutor_DoParallel_Call) Run(run func(ctx context.Context, name string, tasks []executor.Task)) *MockExecutor_DoParallel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]executor.Task))
	})
	return _c
}

func (_c *MockExecutor_DoParallel_Call) Return(_a0 error) *MockExecutor_DoParallel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_DoParallel_Call) RunAndReturn(run func(context.Context, string, []executor.Task) error) *MockExecutor_DoParallel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
