// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, name, fn
func (_m *MockExecutor) Do(ctx context.Context, name string, fn func(context.Context)) {
	_m.Called(ctx, name, fn)
}

// MockExecutor_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockExecutor_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - fn func(context.Context)
func (_e *MockExecutor_Expecter) Do(ctx interface{}, name interface{}, fn interface{}) *MockExecutor_Do_Call {
	return &MockExecutor_Do_Call{Call: _e.mock.On("Do", ctx, name, fn)}
}

func (_c *MockExecutor_Do_Call) Run(run func(ctx context.Context, name string, fn func(context.Context))) *MockExecutor_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context)))
	})
	return _c
}

func (_c *MockExecutor_Do_Call) Return() *MockExecutor_Do_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_Do_Call) RunAndReturn(run func(context.Context, string, func(context.Context))) *MockExecutor_Do_Call {
	_c.Run(run)
	return _c
}

// DoAsync provides a mock function with given fields: ctx, name, fn
func (_m *MockExecutor) DoAsync(ctx context.Context, name string, fn func(context.Context)) {
	_m.Called(ctx, name, fn)
}

// MockExecutor_DoAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoAsync'
type MockExecutor_DoAsync_Call struct {
	*mock.Call
}

// DoAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - fn func(context.Context)
func (_e *MockExecutor_Expecter) DoAsync(ctx interface{}, name interface{}, fn interface{}) *MockExecutor_DoAsync_Call {
	return &MockExecutor_DoAsync_Call{Call: _e.mock.On("DoAsync", ctx, name, fn)}
}

func (_c *MockExecutor_DoAsync_Call) Run(run func(ctx context.Context, name string, fn func(context.Context))) *MockExecutor_DoAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context)))
	})
	return _c
}

func (_c *MockExecutor_DoAsync_Call) Return() *MockExecutor_DoAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_DoAsync_Call) RunAndReturn(run func(context.Context, string, func(context.Context))) *MockExecutor_DoAsync_Call {
	_c.Run(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
