// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserResolver is an autogenerated mock type for the UserResolver type
type MockUserResolver struct {
	mock.Mock
}

type MockUserResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserResolver) EXPECT() *MockUserResolver_Expecter {
	return &MockUserResolver_Expecter{mock: &_m.Mock}
}

// IDsByUIDs provides a mock function with given fields: ctx, userUIDs
func (_m *MockUserResolver) IDsByUIDs(ctx context.Context, userUIDs []string) (map[string]int64, error) {
	ret := _m.Called(ctx, userUIDs)

	if len(ret) == 0 {
		panic("no return value specified for IDsByUIDs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, userUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, userUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, userUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserResolver_IDsByUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByUIDs'
type MockUserResolver_IDsByUIDs_Call struct {
	*mock.Call
}

// IDsByUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userUIDs []string
func (_e *MockUserResolver_Expecter) IDsByUIDs(ctx interface{}, userUIDs interface{}) *MockUserResolver_IDsByUIDs_Call {
	return &MockUserResolver_IDsByUIDs_Call{Call: _e.mock.On("IDsByUIDs", ctx, userUIDs)}
}

func (_c *MockUserResolver_IDsByUIDs_Call) Run(run func(ctx context.Context, userUIDs []string)) *MockUserResolver_IDsByUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockUserResolver_IDsByUIDs_Call) Return(_a0 map[string]int64, _a1 error) *MockUserResolver_IDsByUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserResolver_IDsByUIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockUserResolver_IDsByUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UIDsByIDs provides a mock function with given fields: ctx, userIDs
func (_m *MockUserResolver) UIDsByIDs(ctx context.Context, userIDs []int64) (map[int64]string, error) {
	ret := _m.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for UIDsByIDs")
	}

	var r0 map[int64]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]string, error)); ok {
		return rf(ctx, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]string); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserResolver_UIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDsByIDs'
type MockUserResolver_UIDsByIDs_Call struct {
	*mock.Call
}

// UIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []int64
func (_e *MockUserResolver_Expecter) UIDsByIDs(ctx interface{}, userIDs interface{}) *MockUserResolver_UIDsByIDs_Call {
	return &MockUserResolver_UIDsByIDs_Call{Call: _e.mock.On("UIDsByIDs", ctx, userIDs)}
}

func (_c *MockUserResolver_UIDsByIDs_Call) Run(run func(ctx context.Context, userIDs []int64)) *MockUserResolver_UIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockUserResolver_UIDsByIDs_Call) Return(_a0 map[int64]string, _a1 error) *MockUserResolver_UIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserResolver_UIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]string, error)) *MockUserResolver_UIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserResolver creates a new instance of MockUserResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserResolver {
	mock := &MockUserResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
