// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeviceResolver is an autogenerated mock type for the DeviceResolver type
type MockDeviceResolver struct {
	mock.Mock
}

type MockDeviceResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceResolver) EXPECT() *MockDeviceResolver_Expecter {
	return &MockDeviceResolver_Expecter{mock: &_m.Mock}
}

// IDsByUIDs provides a mock function with given fields: ctx, deviceUIDs
func (_m *MockDeviceResolver) IDsByUIDs(ctx context.Context, deviceUIDs []string) (map[string]int64, error) {
	ret := _m.Called(ctx, deviceUIDs)

	if len(ret) == 0 {
		panic("no return value specified for IDsByUIDs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, deviceUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, deviceUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, deviceUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceResolver_IDsByUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByUIDs'
type MockDeviceResolver_IDsByUIDs_Call struct {
	*mock.Call
}

// IDsByUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceUIDs []string
func (_e *MockDeviceResolver_Expecter) IDsByUIDs(ctx interface{}, deviceUIDs interface{}) *MockDeviceResolver_IDsByUIDs_Call {
	return &MockDeviceResolver_IDsByUIDs_Call{Call: _e.mock.On("IDsByUIDs", ctx, deviceUIDs)}
}

func (_c *MockDeviceResolver_IDsByUIDs_Call) Run(run func(ctx context.Context, deviceUIDs []string)) *MockDeviceResolver_IDsByUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockDeviceResolver_IDsByUIDs_Call) Return(_a0 map[string]int64, _a1 error) *MockDeviceResolver_IDsByUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceResolver_IDsByUIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockDeviceResolver_IDsByUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UIDsByIDs provides a mock function with given fields: ctx, deviceIDs
func (_m *MockDeviceResolver) UIDsByIDs(ctx context.Context, deviceIDs []int64) (map[int64]string, error) {
	ret := _m.Called(ctx, deviceIDs)

	if len(ret) == 0 {
		panic("no return value specified for UIDsByIDs")
	}

	var r0 map[int64]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]string, error)); ok {
		return rf(ctx, deviceIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]string); ok {
		r0 = rf(ctx, deviceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, deviceIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceResolver_UIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDsByIDs'
type MockDeviceResolver_UIDsByIDs_Call struct {
	*mock.Call
}

// UIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceIDs []int64
func (_e *MockDeviceResolver_Expecter) UIDsByIDs(ctx interface{}, deviceIDs interface{}) *MockDeviceResolver_UIDsByIDs_Call {
	return &MockDeviceResolver_UIDsByIDs_Call{Call: _e.mock.On("UIDsByIDs", ctx, deviceIDs)}
}

func (_c *MockDeviceResolver_UIDsByIDs_Call) Run(run func(ctx context.Context, deviceIDs []int64)) *MockDeviceResolver_UIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockDeviceResolver_UIDsByIDs_Call) Return(_a0 map[int64]string, _a1 error) *MockDeviceResolver_UIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceResolver_UIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]string, error)) *MockDeviceResolver_UIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceResolver creates a new instance of MockDeviceResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceResolver {
	mock := &MockDeviceResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
