// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	resolver "github.com/adityakw90/service-user/internal/core/port/resolver"
	mock "github.com/stretchr/testify/mock"
)

// MockResolverProvider is an autogenerated mock type for the ResolverProvider type
type MockResolverProvider struct {
	mock.Mock
}

type MockResolverProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolverProvider) EXPECT() *MockResolverProvider_Expecter {
	return &MockResolverProvider_Expecter{mock: &_m.Mock}
}

// Device provides a mock function with no fields
func (_m *MockResolverProvider) Device() resolver.DeviceResolver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Device")
	}

	var r0 resolver.DeviceResolver
	if rf, ok := ret.Get(0).(func() resolver.DeviceResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.DeviceResolver)
		}
	}

	return r0
}

// MockResolverProvider_Device_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Device'
type MockResolverProvider_Device_Call struct {
	*mock.Call
}

// Device is a helper method to define mock.On call
func (_e *MockResolverProvider_Expecter) Device() *MockResolverProvider_Device_Call {
	return &MockResolverProvider_Device_Call{Call: _e.mock.On("Device")}
}

func (_c *MockResolverProvider_Device_Call) Run(run func()) *MockResolverProvider_Device_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverProvider_Device_Call) Return(_a0 resolver.DeviceResolver) *MockResolverProvider_Device_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolverProvider_Device_Call) RunAndReturn(run func() resolver.DeviceResolver) *MockResolverProvider_Device_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with no fields
func (_m *MockResolverProvider) User() resolver.UserResolver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 resolver.UserResolver
	if rf, ok := ret.Get(0).(func() resolver.UserResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.UserResolver)
		}
	}

	return r0
}

// MockResolverProvider_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockResolverProvider_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *MockResolverProvider_Expecter) User() *MockResolverProvider_User_Call {
	return &MockResolverProvider_User_Call{Call: _e.mock.On("User")}
}

func (_c *MockResolverProvider_User_Call) Run(run func()) *MockResolverProvider_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverProvider_User_Call) Return(_a0 resolver.UserResolver) *MockResolverProvider_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolverProvider_User_Call) RunAndReturn(run func() resolver.UserResolver) *MockResolverProvider_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResolverProvider creates a new instance of MockResolverProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolverProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolverProvider {
	mock := &MockResolverProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
