// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	param "github.com/adityakw90/service-user/internal/core/domain/param"
	mock "github.com/stretchr/testify/mock"
)

// MockDeviceResolver is an autogenerated mock type for the DeviceResolver type
type MockDeviceResolver struct {
	mock.Mock
}

type MockDeviceResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceResolver) EXPECT() *MockDeviceResolver_Expecter {
	return &MockDeviceResolver_Expecter{mock: &_m.Mock}
}

// IDsByUIDs provides a mock function with given fields: ctx, uids
func (_m *MockDeviceResolver) IDsByUIDs(ctx context.Context, uids []string) (map[string]int64, error) {
	ret := _m.Called(ctx, uids)

	if len(ret) == 0 {
		panic("no return value specified for IDsByUIDs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, uids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, uids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceResolver_IDsByUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByUIDs'
type MockDeviceResolver_IDsByUIDs_Call struct {
	*mock.Call
}

// IDsByUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - uids []string
func (_e *MockDeviceResolver_Expecter) IDsByUIDs(ctx interface{}, uids interface{}) *MockDeviceResolver_IDsByUIDs_Call {
	return &MockDeviceResolver_IDsByUIDs_Call{Call: _e.mock.On("IDsByUIDs", ctx, uids)}
}

func (_c *MockDeviceResolver_IDsByUIDs_Call) Run(run func(ctx context.Context, uids []string)) *MockDeviceResolver_IDsByUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockDeviceResolver_IDsByUIDs_Call) Return(_a0 map[string]int64, _a1 error) *MockDeviceResolver_IDsByUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceResolver_IDsByUIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockDeviceResolver_IDsByUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: ctx, opts
func (_m *MockDeviceResolver) Invalidate(ctx context.Context, opts ...param.InvalidateOpt) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...param.InvalidateOpt) error); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceResolver_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockDeviceResolver_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...param.InvalidateOpt
func (_e *MockDeviceResolver_Expecter) Invalidate(ctx interface{}, opts ...interface{}) *MockDeviceResolver_Invalidate_Call {
	return &MockDeviceResolver_Invalidate_Call{Call: _e.mock.On("Invalidate",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockDeviceResolver_Invalidate_Call) Run(run func(ctx context.Context, opts ...param.InvalidateOpt)) *MockDeviceResolver_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]param.InvalidateOpt, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(param.InvalidateOpt)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDeviceResolver_Invalidate_Call) Return(_a0 error) *MockDeviceResolver_Invalidate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceResolver_Invalidate_Call) RunAndReturn(run func(context.Context, ...param.InvalidateOpt) error) *MockDeviceResolver_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}

// UIDsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockDeviceResolver) UIDsByIDs(ctx context.Context, ids []int64) (map[int64]string, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for UIDsByIDs")
	}

	var r0 map[int64]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]string, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]string); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceResolver_UIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDsByIDs'
type MockDeviceResolver_UIDsByIDs_Call struct {
	*mock.Call
}

// UIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockDeviceResolver_Expecter) UIDsByIDs(ctx interface{}, ids interface{}) *MockDeviceResolver_UIDsByIDs_Call {
	return &MockDeviceResolver_UIDsByIDs_Call{Call: _e.mock.On("UIDsByIDs", ctx, ids)}
}

func (_c *MockDeviceResolver_UIDsByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockDeviceResolver_UIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockDeviceResolver_UIDsByIDs_Call) Return(_a0 map[int64]string, _a1 error) *MockDeviceResolver_UIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceResolver_UIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]string, error)) *MockDeviceResolver_UIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceResolver creates a new instance of MockDeviceResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceResolver {
	mock := &MockDeviceResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
