// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-user/internal/core/domain/param"
)

// MockUserPinRepository is an autogenerated mock type for the UserPinRepository type
type MockUserPinRepository struct {
	mock.Mock
}

type MockUserPinRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserPinRepository) EXPECT() *MockUserPinRepository_Expecter {
	return &MockUserPinRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userPin
func (_m *MockUserPinRepository) Create(ctx context.Context, userPin *model.UserPin) (*model.UserPin, error) {
	ret := _m.Called(ctx, userPin)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserPin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserPin) (*model.UserPin, error)); ok {
		return rf(ctx, userPin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserPin) *model.UserPin); ok {
		r0 = rf(ctx, userPin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserPin) error); ok {
		r1 = rf(ctx, userPin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserPinRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserPinRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userPin *model.UserPin
func (_e *MockUserPinRepository_Expecter) Create(ctx interface{}, userPin interface{}) *MockUserPinRepository_Create_Call {
	return &MockUserPinRepository_Create_Call{Call: _e.mock.On("Create", ctx, userPin)}
}

func (_c *MockUserPinRepository_Create_Call) Run(run func(ctx context.Context, userPin *model.UserPin)) *MockUserPinRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserPin))
	})
	return _c
}

func (_c *MockUserPinRepository_Create_Call) Return(_a0 *model.UserPin, _a1 error) *MockUserPinRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserPinRepository_Create_Call) RunAndReturn(run func(context.Context, *model.UserPin) (*model.UserPin, error)) *MockUserPinRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userPin
func (_m *MockUserPinRepository) Delete(ctx context.Context, userPin *model.UserPin) error {
	ret := _m.Called(ctx, userPin)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserPin) error); ok {
		r0 = rf(ctx, userPin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserPinRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserPinRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userPin *model.UserPin
func (_e *MockUserPinRepository_Expecter) Delete(ctx interface{}, userPin interface{}) *MockUserPinRepository_Delete_Call {
	return &MockUserPinRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userPin)}
}

func (_c *MockUserPinRepository_Delete_Call) Run(run func(ctx context.Context, userPin *model.UserPin)) *MockUserPinRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserPin))
	})
	return _c
}

func (_c *MockUserPinRepository_Delete_Call) Return(_a0 error) *MockUserPinRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserPinRepository_Delete_Call) RunAndReturn(run func(context.Context, *model.UserPin) error) *MockUserPinRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, id
func (_m *MockUserPinRepository) GetByUserID(ctx context.Context, id int64) (*model.UserPin, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.UserPin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.UserPin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.UserPin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserPinRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockUserPinRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserPinRepository_Expecter) GetByUserID(ctx interface{}, id interface{}) *MockUserPinRepository_GetByUserID_Call {
	return &MockUserPinRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, id)}
}

func (_c *MockUserPinRepository_GetByUserID_Call) Run(run func(ctx context.Context, id int64)) *MockUserPinRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserPinRepository_GetByUserID_Call) Return(_a0 *model.UserPin, _a1 error) *MockUserPinRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserPinRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int64) (*model.UserPin, error)) *MockUserPinRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockUserPinRepository) List(ctx context.Context, pagination *param.PaginationParam, filter *param.UserPinListFilterParam) (*model.UserPins, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.UserPins
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserPinListFilterParam) (*model.UserPins, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.UserPinListFilterParam) *model.UserPins); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPins)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.UserPinListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserPinRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserPinRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.UserPinListFilterParam
func (_e *MockUserPinRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockUserPinRepository_List_Call {
	return &MockUserPinRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockUserPinRepository_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.UserPinListFilterParam)) *MockUserPinRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.UserPinListFilterParam))
	})
	return _c
}

func (_c *MockUserPinRepository_List_Call) Return(_a0 *model.UserPins, _a1 error) *MockUserPinRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserPinRepository_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.UserPinListFilterParam) (*model.UserPins, error)) *MockUserPinRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userPin
func (_m *MockUserPinRepository) Update(ctx context.Context, userPin *model.UserPin) error {
	ret := _m.Called(ctx, userPin)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserPin) error); ok {
		r0 = rf(ctx, userPin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserPinRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserPinRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userPin *model.UserPin
func (_e *MockUserPinRepository_Expecter) Update(ctx interface{}, userPin interface{}) *MockUserPinRepository_Update_Call {
	return &MockUserPinRepository_Update_Call{Call: _e.mock.On("Update", ctx, userPin)}
}

func (_c *MockUserPinRepository_Update_Call) Run(run func(ctx context.Context, userPin *model.UserPin)) *MockUserPinRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserPin))
	})
	return _c
}

func (_c *MockUserPinRepository_Update_Call) Return(_a0 error) *MockUserPinRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserPinRepository_Update_Call) RunAndReturn(run func(context.Context, *model.UserPin) error) *MockUserPinRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserPinRepository creates a new instance of MockUserPinRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserPinRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserPinRepository {
	mock := &MockUserPinRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
