// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: claims
func (_m *MockTokenGenerator) GenerateToken(claims *model.TokenClaims) (string, error) {
	ret := _m.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.TokenClaims) (string, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(*model.TokenClaims) string); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*model.TokenClaims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGenerator_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockTokenGenerator_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - claims *model.TokenClaims
func (_e *MockTokenGenerator_Expecter) GenerateToken(claims interface{}) *MockTokenGenerator_GenerateToken_Call {
	return &MockTokenGenerator_GenerateToken_Call{Call: _e.mock.On("GenerateToken", claims)}
}

func (_c *MockTokenGenerator_GenerateToken_Call) Run(run func(claims *model.TokenClaims)) *MockTokenGenerator_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TokenClaims))
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateToken_Call) Return(_a0 string, _a1 error) *MockTokenGenerator_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGenerator_GenerateToken_Call) RunAndReturn(run func(*model.TokenClaims) (string, error)) *MockTokenGenerator_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *MockTokenGenerator) ValidateToken(token string) (*model.TokenClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *model.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.TokenClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *model.TokenClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGenerator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenGenerator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenGenerator_Expecter) ValidateToken(token interface{}) *MockTokenGenerator_ValidateToken_Call {
	return &MockTokenGenerator_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockTokenGenerator_ValidateToken_Call) Run(run func(token string)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) Return(_a0 *model.TokenClaims, _a1 error) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) RunAndReturn(run func(string) (*model.TokenClaims, error)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
