// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-user/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, claims
func (_m *MockTokenManager) Generate(ctx context.Context, claims *model.TokenClaims) (string, error) {
	ret := _m.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TokenClaims) (string, error)); ok {
		return rf(ctx, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TokenClaims) string); ok {
		r0 = rf(ctx, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TokenClaims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenManager_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenManager_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *model.TokenClaims
func (_e *MockTokenManager_Expecter) Generate(ctx interface{}, claims interface{}) *MockTokenManager_Generate_Call {
	return &MockTokenManager_Generate_Call{Call: _e.mock.On("Generate", ctx, claims)}
}

func (_c *MockTokenManager_Generate_Call) Run(run func(ctx context.Context, claims *model.TokenClaims)) *MockTokenManager_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.TokenClaims))
	})
	return _c
}

func (_c *MockTokenManager_Generate_Call) Return(_a0 string, _a1 error) *MockTokenManager_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenManager_Generate_Call) RunAndReturn(run func(context.Context, *model.TokenClaims) (string, error)) *MockTokenManager_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, tokenStr
func (_m *MockTokenManager) Revoke(ctx context.Context, tokenStr string) error {
	ret := _m.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenStr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenManager_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenManager_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenStr string
func (_e *MockTokenManager_Expecter) Revoke(ctx interface{}, tokenStr interface{}) *MockTokenManager_Revoke_Call {
	return &MockTokenManager_Revoke_Call{Call: _e.mock.On("Revoke", ctx, tokenStr)}
}

func (_c *MockTokenManager_Revoke_Call) Run(run func(ctx context.Context, tokenStr string)) *MockTokenManager_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenManager_Revoke_Call) Return(_a0 error) *MockTokenManager_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenManager_Revoke_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenManager_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessions provides a mock function with given fields: ctx, userUID
func (_m *MockTokenManager) RevokeAllSessions(ctx context.Context, userUID string) error {
	ret := _m.Called(ctx, userUID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenManager_RevokeAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessions'
type MockTokenManager_RevokeAllSessions_Call struct {
	*mock.Call
}

// RevokeAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
func (_e *MockTokenManager_Expecter) RevokeAllSessions(ctx interface{}, userUID interface{}) *MockTokenManager_RevokeAllSessions_Call {
	return &MockTokenManager_RevokeAllSessions_Call{Call: _e.mock.On("RevokeAllSessions", ctx, userUID)}
}

func (_c *MockTokenManager_RevokeAllSessions_Call) Run(run func(ctx context.Context, userUID string)) *MockTokenManager_RevokeAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenManager_RevokeAllSessions_Call) Return(_a0 error) *MockTokenManager_RevokeAllSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenManager_RevokeAllSessions_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenManager_RevokeAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, userUID, sid
func (_m *MockTokenManager) RevokeSession(ctx context.Context, userUID string, sid string) error {
	ret := _m.Called(ctx, userUID, sid)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userUID, sid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenManager_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockTokenManager_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
//   - sid string
func (_e *MockTokenManager_Expecter) RevokeSession(ctx interface{}, userUID interface{}, sid interface{}) *MockTokenManager_RevokeSession_Call {
	return &MockTokenManager_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, userUID, sid)}
}

func (_c *MockTokenManager_RevokeSession_Call) Run(run func(ctx context.Context, userUID string, sid string)) *MockTokenManager_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenManager_RevokeSession_Call) Return(_a0 error) *MockTokenManager_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenManager_RevokeSession_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTokenManager_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx, tokenStr
func (_m *MockTokenManager) Validate(ctx context.Context, tokenStr string) (*model.TokenClaims, error) {
	ret := _m.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *model.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.TokenClaims, error)); ok {
		return rf(ctx, tokenStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.TokenClaims); ok {
		r0 = rf(ctx, tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenManager_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenManager_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenStr string
func (_e *MockTokenManager_Expecter) Validate(ctx interface{}, tokenStr interface{}) *MockTokenManager_Validate_Call {
	return &MockTokenManager_Validate_Call{Call: _e.mock.On("Validate", ctx, tokenStr)}
}

func (_c *MockTokenManager_Validate_Call) Run(run func(ctx context.Context, tokenStr string)) *MockTokenManager_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenManager_Validate_Call) Return(_a0 *model.TokenClaims, _a1 error) *MockTokenManager_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenManager_Validate_Call) RunAndReturn(run func(context.Context, string) (*model.TokenClaims, error)) *MockTokenManager_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
