// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockUIDGenerator is an autogenerated mock type for the UIDGenerator type
type MockUIDGenerator struct {
	mock.Mock
}

type MockUIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUIDGenerator) EXPECT() *MockUIDGenerator_Expecter {
	return &MockUIDGenerator_Expecter{mock: &_m.Mock}
}

// New provides a mock function with no fields
func (_m *MockUIDGenerator) New() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUIDGenerator_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockUIDGenerator_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *MockUIDGenerator_Expecter) New() *MockUIDGenerator_New_Call {
	return &MockUIDGenerator_New_Call{Call: _e.mock.On("New")}
}

func (_c *MockUIDGenerator_New_Call) Run(run func()) *MockUIDGenerator_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUIDGenerator_New_Call) Return(_a0 string) *MockUIDGenerator_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUIDGenerator_New_Call) RunAndReturn(run func() string) *MockUIDGenerator_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUIDGenerator creates a new instance of MockUIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUIDGenerator {
	mock := &MockUIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
