// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAttemptTracker is an autogenerated mock type for the AttemptTracker type
type MockAttemptTracker struct {
	mock.Mock
}

type MockAttemptTracker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttemptTracker) EXPECT() *MockAttemptTracker_Expecter {
	return &MockAttemptTracker_Expecter{mock: &_m.Mock}
}

// IsLocked provides a mock function with given fields: ctx, userUID
func (_m *MockAttemptTracker) IsLocked(ctx context.Context, userUID string) (bool, error) {
	ret := _m.Called(ctx, userUID)

	if len(ret) == 0 {
		panic("no return value specified for IsLocked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, userUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, userUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttemptTracker_IsLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLocked'
type MockAttemptTracker_IsLocked_Call struct {
	*mock.Call
}

// IsLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
func (_e *MockAttemptTracker_Expecter) IsLocked(ctx interface{}, userUID interface{}) *MockAttemptTracker_IsLocked_Call {
	return &MockAttemptTracker_IsLocked_Call{Call: _e.mock.On("IsLocked", ctx, userUID)}
}

func (_c *MockAttemptTracker_IsLocked_Call) Run(run func(ctx context.Context, userUID string)) *MockAttemptTracker_IsLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAttemptTracker_IsLocked_Call) Return(_a0 bool, _a1 error) *MockAttemptTracker_IsLocked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttemptTracker_IsLocked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockAttemptTracker_IsLocked_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: ctx, userUID
func (_m *MockAttemptTracker) Reset(ctx context.Context, userUID string) error {
	ret := _m.Called(ctx, userUID)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttemptTracker_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockAttemptTracker_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
func (_e *MockAttemptTracker_Expecter) Reset(ctx interface{}, userUID interface{}) *MockAttemptTracker_Reset_Call {
	return &MockAttemptTracker_Reset_Call{Call: _e.mock.On("Reset", ctx, userUID)}
}

func (_c *MockAttemptTracker_Reset_Call) Run(run func(ctx context.Context, userUID string)) *MockAttemptTracker_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAttemptTracker_Reset_Call) Return(_a0 error) *MockAttemptTracker_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttemptTracker_Reset_Call) RunAndReturn(run func(context.Context, string) error) *MockAttemptTracker_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function with given fields: ctx, userUID
func (_m *MockAttemptTracker) Track(ctx context.Context, userUID string) error {
	ret := _m.Called(ctx, userUID)

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttemptTracker_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockAttemptTracker_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - ctx context.Context
//   - userUID string
func (_e *MockAttemptTracker_Expecter) Track(ctx interface{}, userUID interface{}) *MockAttemptTracker_Track_Call {
	return &MockAttemptTracker_Track_Call{Call: _e.mock.On("Track", ctx, userUID)}
}

func (_c *MockAttemptTracker_Track_Call) Run(run func(ctx context.Context, userUID string)) *MockAttemptTracker_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAttemptTracker_Track_Call) Return(_a0 error) *MockAttemptTracker_Track_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttemptTracker_Track_Call) RunAndReturn(run func(context.Context, string) error) *MockAttemptTracker_Track_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttemptTracker creates a new instance of MockAttemptTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttemptTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttemptTracker {
	mock := &MockAttemptTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
