// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domainevent "github.com/adityakw90/service-user/internal/core/domain/event"

	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockEventPublisher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventPublisher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEventPublisher_Expecter) Close() *MockEventPublisher_Close_Call {
	return &MockEventPublisher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEventPublisher_Close_Call) Run(run func()) *MockEventPublisher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventPublisher_Close_Call) Return(_a0 error) *MockEventPublisher_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_Close_Call) RunAndReturn(run func() error) *MockEventPublisher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockEventPublisher) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEventPublisher_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockEventPublisher_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockEventPublisher_Expecter) Name() *MockEventPublisher_Name_Call {
	return &MockEventPublisher_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockEventPublisher_Name_Call) Run(run func()) *MockEventPublisher_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventPublisher_Name_Call) Return(_a0 string) *MockEventPublisher_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_Name_Call) RunAndReturn(run func() string) *MockEventPublisher_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, eventType, eventData
func (_m *MockEventPublisher) Publish(ctx context.Context, eventType domainevent.EventType, eventData interface{}) error {
	ret := _m.Called(ctx, eventType, eventData)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domainevent.EventType, interface{}) error); ok {
		r0 = rf(ctx, eventType, eventData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType domainevent.EventType
//   - eventData interface{}
func (_e *MockEventPublisher_Expecter) Publish(ctx interface{}, eventType interface{}, eventData interface{}) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, eventType, eventData)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(ctx context.Context, eventType domainevent.EventType, eventData interface{})) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domainevent.EventType), args[2].(interface{}))
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return(_a0 error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(context.Context, domainevent.EventType, interface{}) error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
